NordSecurity/libdrop

drop-transfer/src/protocol/v3.rs, drop-transfer/src/ws/server/mod.rs, test/drop_test/action.py, test/drop_test/event.py, test/drop_test/ffi.py, test/scenarios.py
As in the title. I wrote a test for file resuming and one for resuming but with invalid temporary file, to check if this prevents from reusing the file
=> File resume tests

changelog.md, norddrop/ffi/bindings/android/wrap/java_wrap.c, norddrop/ffi/norddropjava.i
As in the title. This fixes java binding issue
=> java binding does not work

changelog.md, norddrop/ffi/bindings/android/wrap/java_wrap.c, norddrop/ffi/norddropjava.i, norddrop/src/device/mod.rs
There was a missing `NULL` check, fixed that. Also, I've added printing the keys (public and private) on debug build
=> Java binding still does not work

norddrop/src/device/mod.rs
I've added the log just for debugging purposes but I think it's useful to leave it there
=> print pubkey decode error

drop-transfer/src/error.rs, norddrop/src/device/types.rs, test/drop_test/action.py, test/drop_test/event.py, test/drop_test/ffi.py, test/drop_test/scenario.py, test/run.py, test/scenarios.py
I've included the OS error code in the event status. I've also made a test case to check for if the lack of permissions (OS error 13) triggers an event with proper status
=> Receiver does not get proper error message on error

.github/workflows/lint.yml
This reverts commit a6698699e586e1202b0e81c174381e3250b6ed8a.
=> Revert ".github: workflows: lint: Check out HEAD of PR target"

drop-transfer/src/ws/client/v2.rs, drop-transfer/src/ws/client/v4.rs, drop-transfer/src/ws/server/mod.rs, test/drop_test/action.py, test/scenarios.py
This PR includes an integration test and a fix for the issue
=> Deleting temp file results in success for the sender

Cargo.lock, Cargo.toml, drop-core/Cargo.toml, drop-core/src/lib.rs, drop-core/src/status.rs, drop-storage/src/error.rs, drop-storage/src/lib.rs, drop-transfer/Cargo.toml, drop-transfer/src/error.rs, norddrop/Cargo.toml, norddrop/src/device/mod.rs, norddrop/src/device/types.rs, test/drop_test/config.py, test/drop_test/error.py, test/drop_test/event.py, test/drop_test/ffi.py, test/drop_test/scenario.py, test/run.py, test/scenarios.py
I'm not sure if we want to do this on each runtime DB error
=> Automatically remove database on error

Cargo.lock, drop-storage/Cargo.toml
This PR should fix the time security issue reported be dependabot
=> Remove chrono time dependency

changelog.md, drop-analytics/src/lib.rs, drop-analytics/src/mock_impl.rs, drop-analytics/src/moose_impl.rs, norddrop/src/device/mod.rs
Try to open database in memory if path fails, in addition, send off the errors with moose
=> Database open error handing

drop-transfer/examples/udrop.rs, drop-transfer/src/event.rs, drop-transfer/src/file/id.rs, drop-transfer/src/file/mod.rs, drop-transfer/src/lib.rs, drop-transfer/src/manager.rs, drop-transfer/src/protocol/v1.rs, drop-transfer/src/protocol/v5.rs, drop-transfer/src/service.rs, drop-transfer/src/storage_dispatch.rs, drop-transfer/src/transfer.rs, drop-transfer/src/ws/client/handler.rs, drop-transfer/src/ws/client/mod.rs, drop-transfer/src/ws/client/v2.rs, drop-transfer/src/ws/client/v4.rs, drop-transfer/src/ws/client/v5.rs, drop-transfer/src/ws/server/handler.rs, drop-transfer/src/ws/server/mod.rs, drop-transfer/src/ws/server/v2.rs, drop-transfer/src/ws/server/v4.rs, drop-transfer/src/ws/server/v5.rs, norddrop/src/device/mod.rs, norddrop/src/device/types.rs
The title says it all. Enjoy :)
=> split Transfer type into IncomingTransfer and OutgoingTransfer types

test/scenarios.py
Notable changes:
scenario4-7,9,13 Deleted (sender side rejections)
scenario10-1,2 Disabled for now, since they should be relevant again after implementing events for transfer resumes/stops
scenario10-3 Deleted as it's no longer relevant
=> Update tests after automated retries

drop-transfer/src/file/mod.rs, drop-transfer/src/manager.rs, test/scenarios.py
=> fix relative path not being inserted into DB

drop-transfer/src/ws/client/mod.rs, test/drop_test/action.py, test/drop_test/ffi.py, test/scenarios.py
Softening the transfer failure conditions
=> Some client connection errors should not abort the retires

Cargo.lock, drop-analytics/src/file_impl.rs, drop-analytics/src/lib.rs, drop-analytics/src/mock_impl.rs, drop-analytics/src/moose_impl.rs, drop-storage/Cargo.toml, drop-transfer/src/file/mod.rs, drop-transfer/src/protocol/mod.rs, drop-transfer/src/service.rs, drop-transfer/src/transfer.rs, drop-transfer/src/ws/client/mod.rs, drop-transfer/src/ws/events.rs, test/scenarios.py
Notable changes include the removal of the `Phase` field in all events, the addition of `TransferDirection` and `protocol_version` fields
In addtion, we had to downgrade our version of `chrono` to satisfy the version requested by moose
=> Update Moose to v0.5.1

.github/workflows/integration-tests.yml, .gitignore, README.md, test/Makefile, test/docker-compose.yml, test/drop_test/scenario.py, test/run.py, test/runner.py, test/scenarios.py
Allows tests(whole and individual) to be executed using `make`.
Introduces coverage for whole test suite and individual tests
=> File 430 code coverage

drop-storage/src/lib.rs, drop-storage/src/types.rs, drop-transfer/src/storage_dispatch.rs, norddrop/src/device/mod.rs
Removing unused code + simple refactors
=> Code cleanup

test/scenarios.py
Three more rejection test cases
=> Add more rejections test cases

changelog.md, drop-config/src/lib.rs, drop-transfer/src/service.rs, drop-transfer/src/ws/server/mod.rs, norddrop/ffi/bindings/norddrop.h, norddrop/src/device/types.rs, norddrop/src/ffi/mod.rs
Removed params:
* `max_uploads_in_flight`
* `max_requests_per_sec`
=> Remove undocumented config parameters

changelog.md, drop-storage/migrations/003-retries/up.sql, drop-storage/src/lib.rs, drop-storage/src/types.rs
=> Remove transfer active state since is never inserted into db

drop-config/src/lib.rs, drop-transfer/src/ws/client/handler.rs, drop-transfer/src/ws/client/mod.rs, drop-transfer/src/ws/client/socket.rs, drop-transfer/src/ws/client/v2.rs, drop-transfer/src/ws/client/v4.rs, drop-transfer/src/ws/client/v5.rs, drop-transfer/src/ws/server/handler.rs, drop-transfer/src/ws/server/mod.rs, drop-transfer/src/ws/server/socket.rs, drop-transfer/src/ws/server/v2.rs, drop-transfer/src/ws/server/v4.rs, drop-transfer/src/ws/server/v5.rs, drop-transfer/src/ws/utils.rs
This PR abstracts away the socket into a custom type that imposes timeouts automatically
=> Fix: Android reported a huge 17 min delay for receiving paused events

drop-storage/src/lib.rs
Blocked by https://github.com/NordSecurity/libdrop/pull/191
=> Purge transfers should check for state

.github/workflows/lint.yml, drop-transfer/src/ws/server/mod.rs, test/Dockerfile, test/drop_test/action.py, test/drop_test/ffi.py, test/scenarios.py
Warp filters were checked in order, so I reordered it so that the DDoS filter is triggered first
=> Fix DDoS test case + improve when the protection is triggered

drop-transfer/src/check.rs, drop-transfer/src/service.rs, drop-transfer/src/utils.rs, drop-transfer/src/ws/client/mod.rs, drop-transfer/src/ws/server/mod.rs
This PR implements the client socket binding to a specific local IP address before connecting
=> Fix client sockets binding to the wrong IP

test/drop_test/ffi.py, test/drop_test/peer_resolver.py, test/scenarios.py
Found that Peer is unused and simplified code by using OS calls for resolving. scenario28 now passes properly
=> Fix runner for ipv6

drop-auth/src/http.rs, drop-storage/src/lib.rs, drop-storage/src/sync.rs, drop-storage/src/types.rs, drop-transfer/src/file/id.rs, drop-transfer/src/file/mod.rs, drop-transfer/src/manager.rs, drop-transfer/src/protocol/v1.rs, drop-transfer/src/protocol/v4.rs, drop-transfer/src/protocol/v5.rs, drop-transfer/src/transfer.rs, drop-transfer/src/utils.rs, drop-transfer/src/ws/server/handler.rs, norddrop/src/device/types.rs, norddrop/src/ffi/types.rs, test/Makefile, test/drop_test/action.py, test/scenarios.py
* Removed unused code
* Added test cases
Scenario 31-8 fails, but it's a bug in the codebase. So I left it there and created a ticket for the next PR
=> Make use of the coverage data

Cargo.lock, drop-transfer/Cargo.toml
Basically it's just tungstenite and warp version bumps
=> Fix: https://github.com/NordSecurity/libdrop/security/dependabot/7

.github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yaml, drop-transfer/src/manager.rs, drop-transfer/src/ws/client/handler.rs, drop-transfer/src/ws/client/mod.rs, drop-transfer/src/ws/client/v2.rs, drop-transfer/src/ws/client/v4.rs, drop-transfer/src/ws/client/v5.rs, drop-transfer/src/ws/server/mod.rs, drop-transfer/src/ws/server/v2.rs, drop-transfer/src/ws/server/v4.rs, drop-transfer/src/ws/server/v5.rs, norddrop/src/ffi/mod.rs
=> Rust 1.72.1 - main edition

test/scenarios.py
This PR fixes problems which appeared as a result of merging `main` into `dev`
=> Fix integraion tests code

drop-analytics/src/file_impl.rs
These were giving compiler warnings. So I removed them
=> Remove unused imports in the analytics file impl

test/drop_test/action.py, test/scenarios.py
I've tried to run the workflow several times by now and it's more or less green
=> tests: reduce flakyness of the test cases

drop-storage/migrations/001-initial/up.sql, drop-transfer/src/error.rs, drop-transfer/src/service.rs, test/drop_test/action.py, test/scenarios.py
I've removed todo which seemed unrealistic or redundant to me
=> Remove TODO comments

norddrop/ffi/bindings/norddrop.h, norddrop/src/ffi/mod.rs
* Removed the cluttering SQL schema information
* Clarified the argument and result timestamp formats
=> Clarify `norddrop_get_transfers_since()` doc comment

norddrop/ffi/bindings/norddrop.h, norddrop/src/ffi/mod.rs
=> Update norddrpo_get_transfers_since() API example

drop-config/src/lib.rs, drop-transfer/examples/udrop.rs, drop-transfer/src/event.rs, drop-transfer/src/file/mod.rs, drop-transfer/src/storage_dispatch.rs, drop-transfer/src/ws/client/v4.rs, drop-transfer/src/ws/client/v6.rs, drop-transfer/src/ws/events.rs, drop-transfer/src/ws/server/handler.rs, drop-transfer/src/ws/server/mod.rs, drop-transfer/src/ws/server/v2.rs, drop-transfer/src/ws/server/v4.rs, drop-transfer/src/ws/server/v6.rs, norddrop/src/device/types.rs, norddrop/src/ffi/mod.rs, test/drop_test/action.py, test/drop_test/event.py, test/drop_test/ffi.py, test/runner.py, test/scenarios.py
New Events:
* ChecksumStarted
* ChecksumProgress
* ChecksumFinished
These events are emited when the file download finished just before the final TrasnferFinished event.
New config options:
* checksum_events_size_threshold_byttes - only emit if the file is equal or bigger than this amount.
=> Implement Checksum events after file download

drop-analytics/src/moose_impl.rs
not sure if i should split this MR up to avoid review strain
=> Update moose to v4.0.1

.github/workflows/analytics-tests.yml, .github/workflows/gitlab.yml, .github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yaml
I've removed redundant triggers for jobs and updated gitlab trigger aciton
=> Fix gitlab pipeline trigger, clean up redundant actions

test/scenarios.py
It moves all test actions into the same container, thus reducing cross-container timing issues
=> Improve DDoS test case

changelog.md, drop-transfer/examples/udrop.rs, drop-transfer/src/event.rs, drop-transfer/src/manager.rs, drop-transfer/src/service.rs, drop-transfer/src/storage_dispatch.rs, drop-transfer/src/ws/events.rs, norddrop/src/device/mod.rs, norddrop/src/device/types.rs, test/drop_test/event.py, test/drop_test/ffi.py, test/scenarios.py
This PR introduced the `TransferPending` event
=> Introduce file pending event

changelog.md, drop-transfer/src/check.rs, drop-transfer/src/manager.rs, drop-transfer/src/ws/client/mod.rs, drop-transfer/src/ws/server/mod.rs
=> Reduce severity of logs regarding transfer cleanup upon cancellation

Cargo.lock, MOOSE_RELEASE_TAG, changelog.md, drop-analytics/src/moose_impl.rs
=> Bump moose to v6.0.0

bindings/generate_bindings.py, bindings/uniffi.toml
This also include the uniffi.toml config file required by csharp bindings.
=> Add uniffi bindings generation script

drop-transfer/src/file/mod.rs, test/scenarios.py
There was a problem in the previous version if the checksum progress granularity is set to a value smaller than 256KB. The progress bytes were not reported correctly. This commit fixes it.
Also make the last checksum progress event to report the file size.
And also add more test scenarios.
=> Fix checksum progress for small granularity

changelog.md, drop-transfer/src/file/id.rs, drop-transfer/src/file/mod.rs, norddrop/src/event.rs, norddrop/src/norddrop.udl, test/drop_test/event.py, test/drop_test/ffi.py, test/scenarios.py
=> Include `base_dir` field in the `RequestQueued` event files

drop-storage/migrations/003-retries/up.sql, drop-storage/migrations/004-sync-cleanup/up.sql
=> Remove the migration for incoming_path_pending_states

Cargo.lock, Cargo.toml, changelog.md, norddrop/Cargo.toml, test/scenarios.py, uniffi-bindgen/Cargo.toml
Sadly, this introduced breaking changes and broke tests. That's why this PR is that big
=> Bump uniffi to 0.28.3
