drop-config/src/lib.rs
drop-transfer/src/file/mod.rs
drop-transfer/src/file/reader/fd.rs
drop-transfer/src/file/reader/mod.rs
drop-transfer/src/file/reader/path.rs
drop-transfer/src/manager.rs
drop-transfer/src/protocol/v3.rs
drop-transfer/src/ws/client/handler.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v3.rs
drop-transfer/src/ws/events.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v3.rs
drop-transfer/src/ws/utils.rs
test/drop_test/ffi.py
test/scenarios.py

I've implemented the handler traits for client and server. 
The protocol right now supports file resuming, but does not recognizes fully downloaded files. I'm leaving this for a separate PR.
I also have no idea how to write the integration test for the resume, for now I only tested this feature with `udrop`

Implement V3 protocol on client and server

---

drop-transfer/src/protocol/v3.rs
drop-transfer/src/service.rs
drop-transfer/src/utils.rs
drop-transfer/src/ws/client/handler.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/client/v3.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v3.rs
test/run.py
test/scenarios.py

Added the check if the file to be downloaded is already there.
Needed to change the V3 protocol a bit because previous iteration didn't allow for multiple checksum requests.
There is still a caveat here. I'm not able to resume and check for existence the directory transfer, because it's really hard do deal with it and I don't even know how. I'm leaving the issue behind since with the use of transfers DB the issue might disappear magically

Do not download the file if its already there

---

Cargo.lock
drop-transfer/Cargo.toml
drop-transfer/src/protocol/v3.rs

This change is mainly for aesthetics and compactness. It will also help in case we need to write the messages by hand during testing

Use hex encoding for the file checsum on the wire

---

changelog.md
norddrop/build.rs

SONAME should be provided by Android libs and is enforced with newer API https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#missing-soname-enforced-for-api-level-23
Similar change has been introduced to libnudler and is on its way to libtelio.

Configure Android SONAME

---

changelog.md
norddrop/src/device/mod.rs

Return moose error only when on non-prod, otherwise just use the mock implementation

Moose init error only on non-prod

---

norddrop/Cargo.toml

Since the platforms builds now specify their own crate types in the command line, we can bring back the lib type for Linux builds.

norddrop: Add lib crate type back

---

norddrop/ffi/bindings/windows/csharp/NordDrop.cs
norddrop/ffi/norddropcs.i

Current declaration was
```
out byte[]
```
Which in C# meant that it must be overwritten
The proper fix is to have
```
byte*
```
This is not as nice however it solves the problem as C# now is able to directly write data to this buffer

Fix C# pubkey callback bindings

---

changelog.md
drop-transfer/src/utils.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v3.rs
drop-transfer/src/ws/server/v4.rs
test/drop_test/config.py
test/scenarios.py

This PR has the following changes:
* change the temp file naming scheme, to avoid conflicts on duplicate names
* test cases for duplicate file names
* making temp -> target rename more atomic
These changes guarantee proper handling of duplicated file names as well as Windows names collision due to the case insensitivity

Sending multiple files with the same filename sends only one

---

.github/workflows/lint.yml

Currently, the checkout action checks out a merge commit, linting code that theoretically does not exist. This commit changes the ref to be the target of the PR.

.github: workflows: lint: Check out HEAD of PR target

---

norddrop/ffi/bindings/android/java/com/nordsec/norddrop/NorddropResult.java
norddrop/ffi/bindings/android/java/com/nordsec/norddrop/libnorddropJNI.java
norddrop/ffi/bindings/android/wrap/java_wrap.c
norddrop/ffi/bindings/linux/go/norddropgo.go
norddrop/ffi/bindings/linux/wrap/go_wrap.c
norddrop/ffi/bindings/norddrop.h
norddrop/ffi/bindings/norddrop_types.h
norddrop/ffi/bindings/windows/csharp/NordDrop.cs
norddrop/ffi/norddropgo.i

There was a typo in the `norddropgo.i` swig file

Fix go bindings for pubkey callback

---

changelog.md
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v4.rs
test/scenarios.py

This PR removes the check for already downloaded files. This feature was introduced along the resumes but turned out to be a bug

Remove check for already downloaded files

---

changelog.md
drop-transfer/src/file/id.rs
drop-transfer/src/file/mod.rs
norddrop/src/device/mod.rs

This is a fix for Windows issues when sending the directories. The `FileSubPath` was parsed incorrectly from the filesystem path

Parse file subpath from the relative path

---

changelog.md
norddrop/ffi/bindings/windows/csharp/NordDrop.cs
norddrop/ffi/bindings/windows/wrap/csharp_wrap.c
norddrop/ffi/norddropcs.i

To be honest it's the only thing we can reasonably do with the C# bindings without writing the wrapper manually

Improve C# bindings

---

norddrop/ffi/bindings/norddrop_types.h
norddrop/src/ffi/types.rs

Public key callback initially passed in NULL
so that the host should return it's own pubkey, however that was changed and is no longer relevant.

Remove outdated comment about NULL param to pubkey cb

---

norddrop/ffi/norddrop.i
norddrop/src/device/mod.rs

The Android team ran into an issue where passing `Long.MAX_VALUE` to `purge_transfers_until` would not delete any of the entries, and according to the SQLite documentation
`These functions only work for dates between 0000-01-01 00:00:00 and 9999-12-31 23:59:59 (julian day numbers 1721059.5 through 5373484.5). For dates outside that range, the results of these functions are undefined.`
To help avoid issues like this in the future, I have added the min and max bounds for the timestamps in the comment of the function

Clarify timestamp input values

---

drop-storage/src/lib.rs
drop-storage/src/types.rs
test/drop_test/action.py
test/scenarios.py

Remove not needed values from the JSON output, to cause less confusion for the app teams

Declutter database JSON output

---

drop-storage/src/lib.rs
drop-storage/src/types.rs
test/scenarios.py

Even more spring cleaning for the JSON output
- Reordered some of the fields to make the output a bit more efficient to visually parse
- Merge both the path and transfer events into one list and sort them by timestamp
And as a side effect-the `types.rs` for storage is a little less bloated

Merge database JSON events into one list

---

norddrop/ffi/bindings/norddrop.h
norddrop/src/ffi/mod.rs
norddrop/src/lib.rs

`cargo doc --open`
now shows the proper docs

Convert existing comments to markdown

---

drop-storage/.sqlx/query-b769b301331cb8c977f22acd9656206ece79c0bd4e7ad711ebb587ded9a9bca2.json
drop-storage/src/lib.rs
drop-storage/src/types.rs
drop-transfer/src/manager.rs
drop-transfer/src/ws/server/mod.rs

So we have this cache of our own created directories in the `TransferManager` but it's stored in RAM and is wiped out on transfer failures.
This PR implements restoring the cache from DB in case the transfer is resumed. It's an alternative to marker files

Fetch preexisting transfer directories on resume

---

test/drop_test/action.py
test/drop_test/ffi.py
test/drop_test/scenario.py
test/scenarios.py

I've extracted the `start()` call into the test cases itself. This enables multiple restarts of the peer inside the test cases and thus we can test the retries.
I've also added 4 basic retries tests

Automated retries tests

---

changelog.md
drop-config/src/lib.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/client/mod.rs
norddrop/src/device/types.rs
norddrop/src/ffi/version.rs

This PR implements limiting the number of files currently being uploaded.
I have two questions:
* Should we also limit the downloads? It seems pretty unreasonable IMHO
* the limit should be imposed on a global, per-transfer, or per-peer basis?

Implement global upload throttle

---

drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
test/drop_test/action.py
test/drop_test/ffi.py
test/scenarios.py

This PR changes the way the names of temp files are created. It uses the Android approach where the transfer UUID is attached to the name.
This basically disables the resumes across different transfers but that's OK, since those are deprecated anyway in favor of auto retries.
I've also had to modify the resume test cases to happen inside a single transfer - which turned out to be buggy (cases 21-1, 21-2, 21-3)

Fxi tempfile collisions across different transfers

---

drop-transfer/src/file/mod.rs
test/scenarios.py

Beefed up the test for insufficient permissions to also check the actual database as well
Also fixed the inconsistency with incoming file `mime_type` and fixed tests after merging main into dev

Verify moose events/in-memory database in integration tests

---

test/scenarios.py

Tests added so far:
- Start a transfer to offline peer, restart both, expect transfer to happen
- Start a transfer to offline peer, reject transfer on sender side, restart both, expect events to be synced and the transfer to not happen
- Start a transfer to offline peer, cancel transfer on sender side, restart both, expect events to be synced and the transfer not to happen
- Complete a normal transfer, restart both sides, check that nothing gets resumed
- Send a transfer to a peer, sender goes offline, receiver accepts while sender is offline, sender goes online, expect transfer to happen properly
- Start a transfer to offline peer, reject transfer on receiver side, restart both, expect events to be synced and the transfer to not happen
- Start a transfer to offline peer, cancel transfer …

Additional retry tests

---

test/drop_test/action.py
test/scenarios.py

Added a sleep to the receiving side, so that the sending side can fist queue up all of the events and as we can no longer guarantee which of the requests get rejected, we wait for one and only one out of the possible three, the only problem that remains is since we don't know which transfer will get rejected, we don't know which to cancel, so one idea would be to not expect the cancels anymore, but not sure if this is the best solution

Stabilize scenario30

---

drop-transfer/src/manager.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/server/mod.rs
test/scenarios.py

This changes how the cancel call is propagated. Instead of implicit API channel close we explicitly use the `Close` request

Android team reported that the transfer can cancel itself

---

drop-transfer/src/file/mod.rs
drop-transfer/src/lib.rs
drop-transfer/src/manager.rs
drop-transfer/src/service.rs
drop-transfer/src/tasks.rs
drop-transfer/src/ws/client/handler.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/client/v4.rs
drop-transfer/src/ws/client/v5.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
test/drop_test/action.py
test/drop_test/scenario.py
test/scenarios.py

Main changes:
* Use `tokio::JoinSet<()>` for efficient tasks cancelation
* 'Asyncify' checksum computation
* Ensure the `stop()` timing with two test cases

Identify and fix causes of a very long time it takes to finish stop() call

---

Cargo.lock
drop-transfer/Cargo.toml
drop-transfer/src/file/mod.rs
drop-transfer/src/file/reader/mod.rs
drop-transfer/src/file/reader/path.rs
drop-transfer/src/manager.rs
drop-transfer/src/ws/events.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
norddrop/src/device/mod.rs
test/drop_test/action.py
test/run.py
test/scenarios.py

This allows for a fairly easy reconstruction of transfer from the database upon instance startup. Previously when restoring a file failed the whole transfer was ignored since it wasn't possible to restore its data structure. With these changes, the structure is restored and the file system is only consulted during the regular operation of the connection handler.
Additionally, I've found a bug with failed and started events sometimes being not emitted on the server side

Allow constructing outgoing files without the access to the file system.

---

norddrop/src/device/mod.rs
test/scenarios.py

Since we decided to use the developer events to catch potential errors in the database creation process, to make the data aggregation step easier, I've shortened the error messages and made them static, so it would be easier to group the error stages and in addition, moved the actual error messages in the notes, allowing us to have finer grained detail on what went wrong, if we need it

Update developer logs for database creation

---

test/runner.py

It enables things like running all 19-* test cases. Useful when testing only a slice of functionality, since a full test is always run on the CI

Use regex for matching the scenario names in the test runner

---

drop-transfer/examples/udrop.rs
drop-transfer/src/ws/client/handler.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/client/v4.rs
drop-transfer/src/ws/client/v5.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs

Emitting events in the handlers `Drop` implementation ensures they are constantly emitted.
This is a preparation for storing progress in the events, so test fixes and including the file progress in the events are going to be included in subsequent PRs

Ensure `Paused` events are emited when stop() is called

---

Cargo.lock
Cargo.toml
drop-core/src/status.rs
drop-storage/Cargo.toml
drop-storage/migrations/003-retries/up.sql
drop-storage/src/lib.rs
drop-storage/src/sync.rs
drop-storage/src/types.rs
drop-transfer/Cargo.toml
drop-transfer/src/error.rs
drop-transfer/src/manager.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/client/handler.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/client/v4.rs
drop-transfer/src/ws/client/v5.rs
drop-transfer/src/ws/events.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
test/drop_test/error.py
test/scenarios.py

This is an attempt to:
* make Rejected, Success, and Failure a terminal state
* do not allow operations on terminated files
* emit events appropriately upon state transition
* sync state transitions upon transfer restoration
A bulk of work is done in the `TransferManager` and the database. The server and client handlers code is basically just adjusted to the changes

Make Rejected, Success and Failure a file terminal states

---

drop-storage/migrations/003-retries/up.sql
drop-storage/src/lib.rs
drop-storage/src/types.rs
drop-transfer/src/storage_dispatch.rs
test/scenarios.py

@LukasPukenis this is the continuation of progress recovery.
I'm not sure about some things:
* is it better to provide global per file field "bytes_transfered" in the JSON API or leave it as it is, as progress inside each state change
* the same question but with the database itself, should we store progress globally or in the `*_states` tables
IMHO it might be beneficial to store and present in the JSON progress as a global per-file thing

Store bytes transfered with paused and reject states

---

drop-storage/src/lib.rs
test/drop_test/error.py
test/scenarios.py

This includes:
* `transfer_since()` unit test
* scenarios.py cleanup and more tests

Ensure tests cover critical v5.0 functionality

---

norddrop/src/device/mod.rs
test/scenarios.py

This is fixed by locking the instance pointer within the libdrop method call and then passing it to the async task.
This avoids concurrent access to the lock, thus eliminating the possibility of reordering locking with respect to method calls

fix panic when stop is called immediately after download

---

changelog.md
drop-config/src/lib.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/client/v4.rs
drop-transfer/src/ws/client/v5.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
drop-transfer/src/ws/utils.rs
norddrop/ffi/bindings/norddrop.h
norddrop/src/device/types.rs
norddrop/src/ffi/mod.rs

Removed params:
* `transfer_idle_lifetime_ms`
* `connection_max_retry_interval_ms`
There are still parameters like:
* `max_uploads_in_flight`
* `max_requests_per_sec`
which are even undocumented
@LukasPukenis what to do with them?

Remove unnecesary and confusing config parameters

---

norddrop/src/device/mod.rs

This was done to aid categorization of these events during aggregation

Unify exception names

---

drop-storage/migrations/003-retries/up.sql
drop-storage/src/lib.rs
drop-storage/src/types.rs
drop-transfer/src/storage_dispatch.rs
test/scenarios.py

This PR uses `Pending` states as a way to inform the app about the file being accepted.
What is more, I've decided that we can store `base_dir` for downloads in the `Pending` states table in contrast to the `Started` states table, since it's more tied to the `download()` call. Details in the commit message

Fix receiving peer cannot know after restarting which files where accepted

---

drop-storage/migrations/003-retries/up.sql
drop-storage/src/lib.rs
drop-transfer/src/manager.rs

This one implements soft deletion for transfers.
The transfers are automatically hard deleted in the library initialization procedure once it's determined that the full state was synced with the peer

Fix: removing transfer from the db prevents the state syncing since the data is lost

---

drop-transfer/src/manager.rs
drop-transfer/src/service.rs
test/drop_test/action.py
test/drop_test/ffi.py
test/drop_test/scenario.py
test/scenarios.py

This PR swaps around `manager::resume` and WebSocket server start. This prevents from broken `norddrop_start()` from trying to communicate with the peer already, failing to accept incoming connections, and producing errors

More tests regarding FFI errors and resume behavior

---

drop-storage/src/lib.rs
drop-transfer/examples/udrop.rs
drop-transfer/src/event.rs
drop-transfer/src/storage_dispatch.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/events.rs
drop-transfer/src/ws/server/mod.rs
norddrop/src/device/types.rs
test/drop_test/action.py
test/drop_test/event.py
test/drop_test/ffi.py
test/scenarios.py

As in the title the `bytes_received` and `bytes_sent` field was not being set up in the DB. Even though it was not declared as `DEFAULT 0`

Fix all the started DB states contained 0 bytes transmitted

---

changelog.md
drop-storage/src/lib.rs
drop-transfer/src/manager.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/socket.rs
test/drop_test/action.py
test/scenarios.py

The issue is that warp (WS server) does not guarantee message delivery on successful flushes - which is probably a bug on their side. This can cause a situation when the receiver thinks the close frame got delivered but in fact, it is not the case, leading to a mismatched transfer state.
Trying to receive from the socket after closing frame seems to catch the problem, though I don't think it catches it in 100% of cases.
Nonetheless, I managed to reproduce the issue with `scenario38` and managed to make it pass, so I don't know what else I could do to improve the implementation

DB error triggered by android app on high latency network

---

drop-transfer/src/manager.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
test/scenarios.py

This feature was requested by the Android team. They wanted to suppress showing the UI for transfers that are going to be canceled immediately

Suppress unseen cancelled transfers syncing

---

changelog.md
drop-config/src/lib.rs
drop-transfer/src/auth.rs
drop-transfer/src/check.rs
drop-transfer/src/lib.rs
drop-transfer/src/manager.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/server/mod.rs
test/scenarios.py

I've implemented two things:
* server endpoint for checking transfer state
* client loop issuing request for this endpoint on the receiver side of things
I've also added a test case, which sadly takes a lot of time to execute

Force recheck from the receiver side for active transfers

---

changelog.md
drop-transfer/src/manager.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs

Is blocked by https://github.com/NordSecurity/libdrop/pull/199
The commit message describes it fully. 
I couldn't reproduce the issue. However, I do see a logic flaw which can lead to it.
There are plenty of test cases that should exercise this (file transferred, then transfer cancelation) and none of them fails spectacularly, suggesting that the issue is super rare to observe

Fix `FileDone` and `TransferCancelation` message reordering

---

drop-storage/migrations/004-sync-cleanup/up.sql
drop-storage/src/lib.rs
drop-storage/src/sync.rs
drop-transfer/src/manager.rs

This removes the `remote` transfer state from the database.
This stems from the discussion with @LukasPukenis that it should be safe to delete this information from the database

Try not to make use of the remote transfer state, kept in the database

---

changelog.md
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/client/v4.rs
drop-transfer/src/ws/client/v5.rs
drop-transfer/src/ws/events.rs
test/scenarios.py

I noticed that the `TransferManager::outgoing_terminal_recv()` already reports that the file is already terminated, just the code inside the clients was simply ignoring it. Hence the event was emitted even though the file was already terminated.
I managed to do a little™ refactor :smile: as well.
I think it best to review this PR commit by commit

Fix: sender emits file finished each time it connects to the receiver

---

changelog.md
drop-transfer/src/ws/client/mod.rs
test/scenarios.py

I've made a test case (failing before the fix) and a fix itself.
The full description of the fix is in the commit message.

fix: still the receiver might get transfer request and transfer cancelled right after each other

---

changelog.md
drop-transfer/examples/udrop.rs
drop-transfer/src/file/gather.rs
drop-transfer/src/file/mod.rs
norddrop/src/device/mod.rs
test/drop_test/config.py
test/prepare_files.sh
test/scenarios.py

This was reported as a bug. So here is the fix.
I've implemented the dedicated file-gathering methods so that it's easier to inspect and reuse those.
The logical change is recording file names in the hash set and checking if the name already exists. If it does then (1), (2),... suffix is added to the subpath's first component.
I'm not sure what to do with the file (not directories) names, it makes 23-1 failing. What do you think?

Fix: sending identical named folders from different paths end up as a single folder with contents merged

---

norddrop/src/device/mod.rs
test/scenarios.py

This basically ensures that all the preconditions (including if it's already started) are met before the actual initialization.
I've also added a test case just to be sure.

Guard `norddrop_start()` from multiple calls

---

Cargo.lock
drop-analytics/Cargo.toml
drop-analytics/src/file_impl.rs
drop-config/src/lib.rs
drop-transfer/src/check.rs
drop-transfer/src/manager.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/client/mod.rs
norddrop/ffi/bindings/android/java/com/nordsec/norddrop/NordDrop.java
norddrop/ffi/bindings/android/java/com/nordsec/norddrop/libnorddropJNI.java
norddrop/ffi/bindings/android/wrap/java_wrap.c
norddrop/ffi/bindings/linux/go/norddropgo.go
norddrop/ffi/bindings/linux/wrap/go_wrap.c
norddrop/ffi/bindings/norddrop.h
norddrop/ffi/bindings/windows/csharp/NordDrop.cs
norddrop/ffi/bindings/windows/wrap/csharp_wrap.c
norddrop/ffi/norddrop.i
norddrop/src/device/mod.rs
norddrop/src/ffi/mod.rs
test/drop_test/action.py
test/drop_test/colors.py
test/drop_test/ffi.py
test/drop_test/logger.py
test/drop_test/peer_resolver.py
test/drop_test/scenario.py
test/runner.py
test/scenarios.py

Introduce `norddrop_set_peer_state(peer, state)` API
---
- removed logic for infinite loop with exponential, capped sleep
- transfer is initiated when:
* libdrop starts
* A new transfer is made
* norddrop_set_peers_state() with `online` flag is passed
- Each testcase became very sensitive to timing as without automated retry if the transfer is initiated from A->B, B is online but libdrop has not yet started it will then return `CONN REFUSED` immediately and without retry logic it will fail. For this, the solution was to add `WaitForAnotherPeer()` in each testcase. An alternative could be to add `norddrop_set_peers_state()` but I didn't see a reason for that.
- `offline` state is actually ignored but I think it's nice to ask for it from the apps as they have that state ready, however not a …

FILE-501 peer online signal

---

test/drop_test/action.py

ipv6 was broken for the upgraded WaitForAnotherPeer() in testrunner

WaitForPeer fixed for ipv6

---

drop-storage/src/lib.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
test/scenarios.py

This PR contains the following changes:
* Ensure that all outstanding tasks are finished before removing temporaries while finalizing
* More logging added
* Try to remove temporaries right away when rejecting

Improve temporaries handling

---

test/scenarios.py

New WaitForAnotherPeer() issues continuous connections towards the peer, this way we're pretty sure when the peer is online. Because peers come online at different times, we need to use it before every transfer issue to ensure the peer availability.
In hindsight - a sleep was OK but I want more determinism in the test runner

Use WaitForAnotherPeer before issuing transfer requests

---

.github/workflows/gitlab.yml

We're migrating runners, so this change is to accomodate to this

Change gitlab trigger runner

---

changelog.md
drop-config/src/lib.rs
drop-transfer/src/check.rs
drop-transfer/src/manager.rs
drop-transfer/src/protocol/v1.rs
drop-transfer/src/protocol/v4.rs
drop-transfer/src/protocol/v5.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v5.rs
norddrop/ffi/bindings/android/java/com/nordsec/norddrop/NordDrop.java
norddrop/ffi/bindings/android/java/com/nordsec/norddrop/libnorddropJNI.java
norddrop/ffi/bindings/android/wrap/java_wrap.c
norddrop/ffi/bindings/linux/go/norddropgo.go
norddrop/ffi/bindings/linux/wrap/go_wrap.c
norddrop/ffi/bindings/norddrop.h
norddrop/ffi/bindings/windows/csharp/NordDrop.cs
norddrop/ffi/bindings/windows/wrap/csharp_wrap.c
norddrop/ffi/norddrop.i
norddrop/src/device/mod.rs
norddrop/src/ffi/mod.rs
test/drop_test/action.py
test/drop_test/ffi.py
test/scenarios.py

simplify code by having umbrella API for network change.
Along came:
- several retries upon the API call as it might be delayed
- fixed infinite check loop
- extra testcase
Adding retries simplified the logic where we don't need to store "refresh was called but the task was busy".
**TLDR:** Inherently this case makes the code behave as in current `main`, except instead of infinite retries it waits for the API to trigger it and gives out several tries.

set_peer_state -> refresh_network

---

norddrop/ffi/bindings/norddrop.h
norddrop/src/ffi/mod.rs

The example in API call was containing
`outgoing` state for the transfer which we don't have anymore

Remove pending mentions from outgoing transfer

---

changelog.md
drop-transfer/src/file/id.rs
drop-transfer/src/file/mod.rs
drop-transfer/src/manager.rs
drop-transfer/src/protocol/v1.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/server/v2.rs
test/scenarios.py

Implemented as agreed on. The drawback is that the transfer is preserved across upgrades from the older protocol to the new one, but I've noticed the problem is there even without normalization so I guess we don't break additional stuff with this PR.
Probably best to review this PR commit by commit

Fix: There is a lack of information in the UI about illegal file names being normalized

---

Cargo.lock

Adding tvOS support requires some dependencies to be updated. In the process I've realized all the dependencies could be updated with a full `cargo update`, with no apparent issues.

build: Run cargo update

---

changelog.md
drop-transfer/examples/udrop.rs
drop-transfer/src/event.rs
drop-transfer/src/service.rs
drop-transfer/src/storage_dispatch.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/throttle.rs
drop-transfer/src/ws/events.rs
norddrop/src/device/types.rs
test/drop_test/action.py
test/drop_test/event.py
test/drop_test/ffi.py
test/scenarios.py

This PR implements emitting an additional event `TransferThrottled` before `TransferStarted` on throttled files

Introduce another file state or event for files being throttled

---

.github/workflows/analytics-tests.yml
drop-transfer/src/check.rs
drop-transfer/src/manager.rs
drop-transfer/src/utils.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/server/mod.rs
test/scenarios.py

This PR fixes a flakiness in some tests, plus some logic errors:
* Improve the reconnection logic, so that the trigger is not ignored while in the backoff loop
* There was a bug where the file was stopped for good on disconnection
I've also split the analytics tests from the regular ones, for easier inspection

fix flaky tests

---

test/scenarios.py

In multi-file transfers, it's not worth to pendatically check for specific file ID's we already know that the batch event contains the correct information, so it should be safe enough, this was the main cause of flakyness, in addition, the check for protocol version has also been made pedantic, as this could in theory help catch a super obscure bug and isn't too big of pain to update, given the frequency of new protocol versions coming out
And also moved all of the analytics tests to be close together

Recude flakyness of analytics tests

---

.github/workflows/analytics-tests.yml
.github/workflows/gitlab.yml
.github/workflows/integration-tests.yml
.github/workflows/unit-tests.yaml

Previous label of `run tests` was obsolete as it actually didn't trigger tests in gitlab but rather internal stuff, so I renamed it.
I also added the same workflow to unit and integration tests. It should trigger the tests after adding the label of `run tests`

Allow for test running via label

---

drop-storage/src/lib.rs
drop-storage/src/types.rs

Improves the performance by reducing the number of queries from a variable number (based on transfers and paths in them) to a constant 3

Use constant number of queries in `transfers_since`

---

Cargo.lock
drop-analytics/src/file_impl.rs
drop-analytics/src/lib.rs
drop-analytics/src/moose_impl.rs
drop-config/src/lib.rs
norddrop/src/device/mod.rs
norddrop/src/device/types.rs
test/drop_test/ffi.py
test/scenarios.py

Notable changes include:
- Context inheritance is automatic, so there is no need for manually retrieving the context from parent tracker
- Context values get updated automatically, so there is no need for periodic update task
- Function signatures had their argument order shuffled around for some reason
- We're still responsible for setting app name and version
- We no longer need to provide the version of the parent application, so this has been removed from the config
(cherry picked from commit bc25fbbd4231631250b33de34242d6d2fb4fcce2)

Backport moose tracker update to v5.4.0

---

changelog.md
drop-transfer/src/ws/events.rs
test/scenarios.py

The issue stems from throttling logic which waits for a semaphore permit. After receiving the permit it emits a `Started` event without any checks.
I've introduced the `Terminal` state in the file event emitter which drops all events emitted after reaching the terminal state.

Forbid emitting file events after reaching termianl state

---

drop-transfer/src/check.rs
drop-transfer/src/manager.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/client/handler.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v2.rs
drop-transfer/src/ws/client/v4.rs
drop-transfer/src/ws/client/v6.rs
drop-transfer/src/ws/events.rs
drop-transfer/src/ws/server/mod.rs

This allows for checks if the transfer is ongoing
and in case of closed transfers suppress event emission.

Emit transfer events from a mutex-protected closed structure

---

changelog.md
drop-transfer/src/ws/server/mod.rs
test/drop_test/config.py
test/prepare_files.sh
test/scenarios.py

This PR changes two things:
* Checks all dir names for being larger than the MAX length, contrary to the current check for only filenames
* Fixes a bug where too-long filenames do not block downloads and are not communicated to the peer as `Failed`

Disallow filenames and dirnames longer than 250 characters

---

changelog.md
drop-transfer/src/manager.rs
test/drop_test/action.py
test/drop_test/event.py
test/scenarios.py

By ensuring there's only one connection for a given transfer at a time we prevent events from mixing with each other

Ensure there is no race condition in events

---

changelog.md
drop-transfer/src/utils.rs

As discussed in the issue ticket, we should ban characters illegal in both FAT and EXT filesystems

Disallow filename characters illega in FAT and EXT filesystems

---

changelog.md
drop-core/src/status.rs
drop-transfer/src/error.rs
test/drop_test/error.py
test/scenarios.py

This commit captures permissions errors from the IO errors and reports them under a separate status code

Add a separate status for permissions error

---

changelog.md
drop-transfer/src/manager.rs
test/drop_test/action.py
test/scenarios.py

When issuing cancel from the receiver while the sender is offline, sometimes the state of files is mismatched for peers.
The solution is to flush the changes to the sender and only then issue the cancel request

Sender and receiver have mismatched file states after transfer cancellation while offline

---

.gitignore
Cargo.lock
Cargo.toml
norddrop/Cargo.toml
norddrop/build.rs
norddrop/src/device/mod.rs
norddrop/src/device/types.rs
norddrop/src/device/utils.rs
norddrop/src/ffi/mod.rs
norddrop/src/ffi/types.rs
norddrop/src/ffi/uni.rs
norddrop/src/lib.rs
norddrop/src/norddrop.udl
test/Makefile
test/drop_test/action.py
test/drop_test/event.py
test/drop_test/ffi.py
test/run.py
test/runner.py
test/scenarios.py
uniffi-bindgen/Cargo.toml
uniffi-bindgen/src/main.rs

This PR adds the following:
* UDL definitions of the library API (`norddrop.udl`)
* DB dump and events are strongly typed
* tests are adjusted to use on-the-fly generated Python bindings
* Rust code adjusted to work well with UDL (`uni.rs`)
I've tried not to touch the current swig-generated API hence everything in the `uni.rs` file just wraps around the ffi device and uses C-style callbacks. This should be flattened after swig removal.
The things left to do after removing the swing bindings
* convert timestamps into `SystemTime` - uniffi has direct conversions to this type
* clean the `uni.rs` file and remove the indirection to the device API (possibly removing the latter one)
So this PR is just the beginning of the changes but I want to get some feedback if things are going in the right …

Introduce uniffi

---

changelog.md
drop-config/src/lib.rs
drop-transfer/src/file/mod.rs
drop-transfer/src/ws/client/v4.rs
drop-transfer/src/ws/client/v6.rs
drop-transfer/src/ws/server/handler.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v2.rs
drop-transfer/src/ws/server/v4.rs
drop-transfer/src/ws/server/v6.rs
norddrop/src/device/types.rs
test/drop_test/action.py
test/drop_test/ffi.py
test/scenarios.py

The problem consists in the fact that while transferring files libdrop will generate ChecksumProgress events for every chunk of data received (256KB) which can be a lot if the file is large.
Setting the checksum_events_granularity config makes the event generation to occur at every checksum_events_granularity chunks of data.

Add checksum_events_granularity config

---

changelog.md

During the checksum granularity PR there was a mistake and the log was added for the wrong release version.

Fix changelog

---

norddrop/src/uni.rs

hardening-check checks if certain symbols are
present in the code. It doesn't confirm
anything else though but it's a step in the
right direction.

Fix Hardening-Check

---

drop-core/src/status.rs
drop-transfer/examples/udrop.rs
drop-transfer/src/event.rs
drop-transfer/src/ws/events.rs
norddrop/src/dump.rs
norddrop/src/event.rs
norddrop/src/norddrop.udl
test/drop_test/action.py
test/drop_test/ffi.py
test/scenarios.py

This PR contains typo fixes `transfered -> transferred` and the second change is using strongly typed statutes for DB dump and subsequent tests fixes

Address typos and types feedback

---

changelog.md
drop-storage/src/lib.rs
drop-transfer/examples/udrop.rs
drop-transfer/src/check.rs
drop-transfer/src/manager.rs
drop-transfer/src/service.rs
drop-transfer/src/ws/client/handler.rs
drop-transfer/src/ws/client/mod.rs
drop-transfer/src/ws/client/v6.rs
drop-transfer/src/ws/server/mod.rs
drop-transfer/src/ws/server/v6.rs
test/scenarios.py

This PR adds the automatic cancelation feature. This is done by checking on each file reaching any terminal state to see if there's any file not yet in the terminal state. If there isn't, the transfer is automatically canceled by the peer who receives the notification about the file state change.
Additionally, I've implemented a check upon establishing the connection to see if the transfer should be canceled based on file states to account for transfers created by old libdrop versions and to be double sure the mechanism works.

Implement automatic transfer cancelation

---

changelog.md
drop-transfer/examples/udrop.rs
drop-transfer/src/auth.rs
drop-transfer/src/ws/server/v6.rs
norddrop/src/device.rs
norddrop/src/uni.rs
test/drop_test/ffi.py
test/runner.py

Private key retrieval was previously done on `device::new()` once and stored, however API users sometimes hcange the private key and need to recreate libdrop instance. However it's no tthe ideal way of doing things and thus this PR just queries for the private key each time it needs.

FILE-613: retrieve private key always

---

Cargo.lock
changelog.md
drop-config/src/lib.rs
drop-transfer/src/service.rs
norddrop/src/config.rs
norddrop/src/norddrop.udl
test/drop_test/action.py
test/drop_test/ffi.py
test/scenarios.py

As in the title. I've needed to update tokio crate to leverage the `tokio::sync::watch::Sender` `Clone` implementation, which was not available in the version we were using before

Implement auto retries under a config feature flag

---

norddrop/build.rs

The binaries for android require to be aligned to 16kB page size

update the page size for android to be 16kB
